# generated by datamodel-codegen:
#   filename:  response-1.json
#   timestamp: 2022-08-04T16:17:13+00:00

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel


class Button(BaseModel):
    title: str
    payload: Dict[str, Any] = None
    url: str = None


class CommandWidget(BaseModel):
    type: str = "Widget"
    payload: Dict[str, Any]
    layout_name: str


class CommandText(BaseModel):
    type: str = "Text"
    text: str = "Тут текст сообщения."


class Push(BaseModel):
    push_text: str
    payload: Dict[str, Any] = None


class Response(BaseModel):
    text: str = ""
    tts: str = ""
    buttons: List[Button] = []
    commands: List[Union[CommandWidget, CommandText]] = []
    push: Union[Push, None] = None
    end_session: bool = True


class User(BaseModel):
    user_id: str


class Application(BaseModel):
    application_id: str
    application_type: str


class Session(BaseModel):
    session_id: str
    user_id: str
    skill_id: str
    new: bool
    message_id: int
    user: User = None
    application: Application


class Model(BaseModel):
    response: Response = Response()
    session: Session
    version: str = "1.0"
