# generated by datamodel-codegen:
#   filename:  request-1.json
#   timestamp: 2022-08-04T16:16:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel

from . import common_model


class Interfaces(BaseModel):
    screen: Union[Dict[str, Any], None] = None


class Meta(BaseModel):
    client_id: str
    locale: str
    timezone: str
    interfaces: Interfaces


class Nlu(BaseModel):
    tokens: List[str]


class Request(BaseModel):
    command: str
    original_utterance: str
    type: str
    payload: Union[Dict[str, Any], None] = None
    nlu: Nlu


class User(BaseModel):
    user_id: str


class Application(BaseModel):
    application_id: str
    application_type: str


class Session(BaseModel):
    session_id: str
    user_id: str
    skill_id: str
    new: bool
    message_id: int
    user: Union[User, None] = None
    application: Application


class UserState(common_model.UserState):
    pass


class SessionState(common_model.SessionState):
    pass


class State(BaseModel):
    session: SessionState
    user: UserState


class Model(BaseModel):
    meta: Meta
    request: Request
    session: Session
    state: Optional[State]
    version: str = "1.0"
