# generated by datamodel-codegen:
#   filename:  response-1.json
#   timestamp: 2022-08-04T16:17:13+00:00

from __future__ import annotations

from typing import Any, Dict, List, Union

from pydantic import BaseModel

from . import common_model


class Button(BaseModel):
    title: str
    payload: Union[Dict[str, Any], None] = None
    url: Union[str, None] = None


class CommandWidget(BaseModel):
    type: str = "Widget"
    payload: Dict[str, Any]
    layout_name: str


class CommandText(BaseModel):
    type: str = "Text"
    text: str = "Тут текст сообщения."


class Push(BaseModel):
    push_text: str
    payload: Union[Dict[str, Any], None] = None


class Response(BaseModel):
    text: str = ""
    tts: str = ""
    buttons: List[Button] = []
    commands: List[Union[CommandWidget, CommandText]] = []
    push: Union[Push, None] = None
    end_session: bool = True


class User(BaseModel):
    user_id: str


class UserStateUpdate(common_model.UserState):
    pass


class SessionStateUpdate(common_model.SessionState):
    pass


class Application(BaseModel):
    application_id: str
    application_type: str


class Session(BaseModel):
    session_id: str
    user_id: str
    message_id: int


class Model(BaseModel):
    response: Response
    session: Union[Session, None] = None
    version: str = "1.0"
    user_state_update: Union[UserStateUpdate, None] = None
    session_state: Union[SessionStateUpdate, None] = None
