# generated by datamodel-codegen:
#   filename:  response-1.json
#   timestamp: 2022-08-04T16:17:13+00:00

from __future__ import annotations

from typing import Any, Dict, List

from pydantic import BaseModel


class Button(BaseModel):
    title: str
    payload: Dict[str, Any]
    url: str


class Response(BaseModel):
    text: str = ""
    tts: str = ""
    buttons: List[Button] = []
    end_session: bool = True


class User(BaseModel):
    user_id: str


class Application(BaseModel):
    application_id: str
    application_type: str


class Session(BaseModel):
    session_id: str
    user_id: str
    skill_id: str
    new: bool
    message_id: int
    user: User = None
    application: Application


class Model(BaseModel):
    response: Response = Response()
    session: Session
    version: str = "1.0"
