name: Deploy Alice skill

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.grammar'
      - '**.txt'

jobs:
  Deploy:
    environment:
      name: Staging
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.YAAUTH }}
          function_id: ${{ secrets.YAFUNCTION_ID }}
          runtime: 'python39'
          memory: '128'
          environment: DIARY_URL=${{ secrets.DIARY_URL }},SENTRY_DSN=${{ secrets.SENTRY_DSN }},DEBUG=False,ENVIRONMENT=Stage
          entrypoint: 'skill.main.handler'
          source: './'
  Production:
    environment:
      name: Production
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - uses: goodsmileduck/yandex-serverless-action@v1
#        with:
#          token: ${{ secrets.YAAUTH }}
#          function_id: ${{ secrets.YAFUNCTION_ID }}
#          runtime: 'python39'
#          memory: '128'
#          environment: DIARY_URL=${{ secrets.DIARY_URL }},SENTRY_DSN=${{ secrets.SENTRY_DSN }},DEBUG=False,ENVIRONMENT=Prod
#          entrypoint: 'skill.main.handler'
#          source: './'
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.YAAUTH }}
          function_id: ${{ secrets.MARUSIA_FUNCTION_ID }}
          runtime: 'python39'
          memory: '128'
          environment: DIARY_URL=${{ secrets.DIARY_URL }},SENTRY_DSN=${{ secrets.SENTRY_DSN }},DEBUG=False,ENVIRONMENT=Stage
          entrypoint: 'endpoints.marusia.yandex.handler'
          source: './'